name: Bug Report
description: If you have a problem or bug with the AuditTAP.
title: "[Bug]: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: Which operating system did the bug occur on?
      options:
        - Windows 10
        - Windows 11
        - Linux
    validations:
      required: true
      
  - type: checkboxes
    id: version_check
    attributes:
      label: Current Version?
      description: Have you already ensured that you are working on our current version of the AuditTAP?
      options:
        - label: This bug occured on version 5.9 of the AuditTAP
          required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
 
  
