name: Bug Report
description: If you have a problem or bug with the AuditTAP.
title: "[Bug]: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Your feedback and support is greatly appreciated, thanks for your time!
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: Which operating system did the bug occur on?
      options:
        - Windows 7
        - Windows 10
        - Windows 11
        - Microsoft Windows 10 Stand-alone
        - Microsoft Windows 11 Stand-alone
        - Microsoft Windows Server 2012
        - Microsoft Windows Server 2016
        - Microsoft Windows Server 2019
        - Microsoft Windows Server 2022
        - Linux - Debian
        - Linux - Fedora
        - Linux - Red Hat
        - Linux - SUSE
      value: " "
      default: 4
    validations:
      required: true
      
  - type: dropdown
    id: report
    attributes:
      label: Report Name
      description: Which report did you execute for the bug to occur?
      options:
        - Microsoft Windows 7
        - Microsoft Windows 10
        - Microsoft Windows 10 GDPR
        - Microsoft Windows 10 BSI
        - Microsoft Windows 10 Stand-alone
        - Microsoft Windows 11 Stand-alone
        - Microsoft Windows 11
        - Microsoft Windows Server 2012
        - Microsoft Windows Server 2016
        - Microsoft Windows Server 2016 DC
        - Microsoft Windows Server 2019
        - Microsoft Windows Server 2019 DC
        - Microsoft Windows Server 2022
        - Microsoft Windows Server 2022 DC
        - Debian 10
        - Debian 11
        - Fedora 35
        - Red Hat Enterprise Linux 8
        - SUSE Linux Enterprise 15
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Google Chrome
        - Mozilla Firefox
        - Microsoft Edge
        - Microsoft Internet Explorer 11
        - Microsoft IIS10
        - Microsoft Office 2016 Excel
        - Microsoft Office 2016 Outlook
        - Microsoft Office 2016 PowerPoint
        - Microsoft Office 2016 SkypeForBusiness
        - Microsoft Office 2016 Word
        - Microsoft Office 2016 
        - Microsoft SQL Server 2016
    validations:
      required: true    
      
  - type: checkboxes
    id: version_check
    attributes:
      label: Current Version?
      description: Have you already ensured that you are working on our current version of the AuditTAP?
      options:
        - label: This bug occured on version 5.9 of the AuditTAP
          required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
 
  
